# Generated by Django 4.1.3 on 2022-12-08 22:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_post_cuerpo_alter_post_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
