# Generated by Django 4.1.3 on 2022-12-13 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0007_remove_post_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='cuerpo',
            new_name='comentario',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
