# Generated by Django 4.1.3 on 2022-12-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_rename_cuerpo_comentario_comentario_remove_post_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(),
        ),
    ]
