# Generated by Django 4.1.3 on 2022-12-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuarioApp', '0007_rename_userprofile_perfiluser_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='slug'),
        ),
    ]
