# Generated by Django 4.1.3 on 2022-12-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsuarioApp', '0008_perfiluser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiluser',
            name='slug',
        ),
    ]
